### ISSUE TITLE
Python Issue

### ISSUE THREAD

**Issue by steveyminecraft** [aws-samples/aws-cdk-tfsec#1]
At present attempting to run the code however this error is being returned. Tired with older versions of the CDK however same error is returned

Software
npm 8.3.1
Python 3.10.2
CDK 2.12.0 (build c9786db)
aws-cli/2.4.3 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

```
cdk bootstrap aws://OPPS/eu-west-2
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Git\aws-cdk-tfsec\app.py", line 5, in <module>
    from aws_cdk import core
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\aws_cdk\core\__init__.py", line 4925, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\aws_cdk\core\__init__.py", line 4963, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: module 'aws_cdk.cx_api' has no attribute 'RuntimeInfo'
```

**Comment by steveyminecraft** [comment]
Have also tired this under ubuntu 20.04 and replicated the same result

**Comment by cesarpball** [comment]
Hi @steveyminecraft 

Thanks for reporting this issue. I want to ask you if you could test two things:

1. Downgrade the CDK version to 1.103.0 (It's not mentioned in the README but the dependencies are set for this particular version)
2. Could you try with Python 3.7 ?  I have tested also with Python 3.9, 3.10 and 3.12 and getting a different issue with the core package of CDK.

Please let me know your tests.

**Comment by cesarpball** [comment]
Hi @steveyminecraft ,

Did you have any chance to review my suggestions?

Regards

**Comment by cesarpball** [comment]
Closing due to inactivity
